music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resource :session, only: [:create, :destroy, :new]

  resources :users, only: [:create, :new, :show]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, except: [:index, :new] do
    resources :tracks, only: [:new]
  end

  resources :tracks, except: [:index, :new]

  resources :notes, only: [:create, :destroy]

  root to: 'sessions#new'
end

music_app/app/models/note.rb
class Note < ApplicationRecord
  validates :description, presence: true

  belongs_to :author,
  primary_key: :id,
  foreign_key: :author_id,
  class_name: :User

  belongs_to :track,
  primary_key: :id,
  foreign_key: :track_id,
  class_name: :Track
end

music_app/app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :current_user_must_be_author, only: [:destroy]

  def create
    @note = Note.new(note_params)
    @note.author_id = current_user.id

    if @note.save
      redirect_to track_url(@note.track_id)
    else
      flash[:errors] = @note.errors.full_messages
      redirect_to track_url(@note.track_id)
    end
  end

  def destroy
    @note = Note.find_by(id: params[:id])

    if @note.destroy
      redirect_to track_url(@note.track_id)
    else
      flash[:errors] = @note.errors.full_messages
      redirect_to track_url(@note.track_id)
    end
  end

  private
  def note_params
    params.require(:note).permit(:track_id, :description)
  end

  def current_user_must_be_author
    current_user_notes = current_user.notes
    note = current_user_notes.find_by(id: params[:id])
    unless note
      render text: 'You cannot delete this note because you are not the author', status: 403
    end
  end
end

music_app/app/views/notes/_form.html.erb
<div class="form_container">
  <form id="create_note_form" action="<%= notes_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="note[track_id]" value="<%= track.id %>">

    <textarea name="note[description]"></textarea>
  </form>
</div>

<div class="button_container">
  <button type="submit" form="create_note_form">Create new note</button>
</div>

music_app/app/views/notes/_note.html.erb
<tr>
  <td><%= note.description %></td>
  <td><%= note.author.email %></td>
  <td>
    <% if current_user == note.author %>
      <form id="delete_note_<%= idx %>" action="<%= note_url(note) %>" method="post">
        <input type="hidden" name="_method" value="delete">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      </form>
      <button type="submit" form="delete_note_<%= idx %>" name="button">Delete</button>
    <% else %>
      <button disabled>Delete</button>
    <% end %>
  </td>
</tr>