music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resource :session, only: [:create, :destroy, :new]

  resources :users, only: [:create, :new, :show]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, except: [:index, :new] do
    resources :tracks, only: [:new]
  end

  resources :tracks, except: [:index, :new]

  resources :notes, only: [:create, :destroy]

  root to: 'sessions#new'
end

music_app/app/models/album.rb
class Album < ApplicationRecord
  validates :title, :year, presence: true
  validates :studio, inclusion: { in: [true, false] }

  belongs_to :band,
  primary_key: :id,
  foreign_key: :band_id,
  class_name: :Band

  has_many :tracks,
  primary_key: :id,
  foreign_key: :album_id,
  class_name: :Track,
  dependent: :destroy
end

music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :require_user_to_be_logged_in

  def index
    @albums = Album.all
    render :index
  end

  def show
    @album = Album.find_by(id: params[:id])

    if @album
      render :show
    else
      flash[:errors] = ["Album does not exist"]
      redirect_to bands_url
    end
  end

  def new
    @album = Album.new
    @album.band_id = params[:band_id]
    @bands = Band.all
    render :new
  end

  def create
    @album = Album.new(album_params)

    if @album.save
      redirect_to album_url(@album)
    else
      flash[:errors] = @album.errors.full_messages
      redirect_to new_band_album_url(@album.band_id)
    end
  end

  def edit
    @album = Album.find_by(id: params[:id])
    @bands = Band.all
    render :edit
  end

  def update
    @album = Album.find_by(id: params[:id])

    if @album.update_attributes(album_params)
      redirect_to album_url(@album)
    else
      flash[:errors] = @album.errors.full_messages
      redirect_to edit_album_url(@album)
    end
  end

  def destroy
    @album = Album.find_by(id: params[:id])

    if @album.destroy
      redirect_to band_url(@album.band_id)
    else
      flash[:errors] = @album.errors.full_messages
      redirect_to album_url(@album)
    end
  end

  private
  def album_params
    params.require(:album).permit(:band_id, :title, :year, :studio)
  end
end

music_app/app/views/albums/edit.html.erb
<h1>Edit an album</h1>

<%= render 'shared/errors' %>

<div class="form_container">
  <form action="<%= album_url %>" method="post">
    <input type="hidden" name="_method" value="patch">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label for="album_band">Band</label>
    <select id="album_band" name="album[band_id]">
      <option disabled <%= @album.band_id.nil? ? "selected" : "" %> >--Select band--</option>
      <% @bands.each do |band| %>
        <option value="<%= band.id %>" <%= @album.band_id == band.id ? "selected" : "" %> ><%= band.name %></option>
      <% end %>
    </select>
    <br>

    <label for="album_title">Title</label>
    <input id="album_title" type="text" name="album[title]" value="<%= @album.title %>">
    <br>

    <label for="album_year">Year</label>
    <input type="number" name="album[year]" value="<%= @album.year %>" min="1900" max="2018">
    <br>

    <div>
      <label for"album_live">Live</label>
      <input id="album_live" type="radio" name="album[studio]" value="false" <%= @album.studio ? "" : "checked" %> >

      <label for="album_studio">Studio</label>
      <input id="album_studio"type="radio" name="album[studio]" value="true" <%= @album.studio ? "checked" : "" %> >
    </div>
    <br>
  </form>
</div>

<div class="button_container">
  <button type="submit" form="edit_album_form">Edit album</button>
</div>

<% content_for :footer do %>
  Album edit page
<% end %>

music_app/app/views/albums/new.html.erb
<h1>Create an album</h1>

<%= render 'shared/errors' %>
<div class="form_container">
  <form action="<%= albums_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label for="album_band">Band:</label>
    <select id="album_band" name="album[band_id]">
      <option disabled <%= @album.band_id.nil? ? "selected" : "" %> >--Select band--</option>
      <% @bands.each do |band| %>
        <option value="<%= band.id %>" <%= @album.band_id == band.id ? "selected" : "" %> ><%= band.name %></option>
      <% end %>
    </select>
    <br>

    <label for="album_title">Title:</label>
    <input id="album_title" type="text" name="album[title]" value="<%= @album.title %>">
    <br>

    <label for="album_year">Year:</label>
    <input type="number" name="album[year]" value="<%= @album.year %>" min="1900" max="2018">
    <br>

    <div>
      <label for="album_studio">Studio</label>
      <input id="album_studio"type="radio" name="album[studio]" value="true" <%= @album.studio ? "checked" : "" %> >
      <label for"album_live">Live</label>
      <input id="album_live" type="radio" name="album[studio]" value="false" <%= @album.studio ? "" : "checked" %> >
    </div>
    <br>

    <input type="submit" value="Create album">

  </form>
</div>

<% content_for :footer do %>
  Album new page
<% end %>

music_app/app/views/albums/show.html.erb
<%= render 'shared/errors' %>

<h1>Album: <%= @album.title %></h1>
<h2>By: <a href="<%= band_url(@album.band_id) %>"><%= @album.band.name %></a></h2>
<h2>Year: <%= @album.year %></h2>
<h2>Type: <%= @album.studio ? "Studio" : "Live" %> </h2>

<div class="button_container">
  <button type="submit" form="edit_album_form">Edit album</button>

  <button type="submit" form="delete_album_form" name="button">Delete album</button>
</div>

<form id="edit_album_form" action="<%= edit_album_url(@album) %>" method="get">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
</form>

<form id="delete_album_form" action="<%= album_url(@album) %>" method="post">
  <input type="hidden" name="_method" value="delete">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
</form>
<br>

<table>
  <tr>
    <th>Track</th>
    <th>Number</th>
    <th>Type</th>
    <th>Page</th>
  </tr>
  <% @album.tracks.each do |track| %>
    <tr>
      <td><%= track.title %></td>
      <td><%= track.ord %></td>
      <td><%= track.bonus ? "Bonus" : "Regular" %></td>
      <td><a href="<%= track_url(track) %>">Link</a></td>
    </tr>
  <% end %>
</table>

<div class="button_container">
  <button type="submit" form="create_track_form">Create track</button>
</div>

<form id="create_track_form" action="<%= new_album_track_url(@album) %>" method="get">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
</form>

<% content_for :footer do %>
  Album show page
<% end %>