music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resource :session, only: [:create, :destroy, :new]

  resources :users, only: [:create, :new, :show]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, except: [:index, :new] do
    resources :tracks, only: [:new]
  end

  resources :tracks, except: [:index, :new]

  resources :notes, only: [:create, :destroy]

  root to: 'sessions#new'
end

music_app/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint(8)        not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates :name, presence: true

  has_many :albums,
  primary_key: :id,
  foreign_key: :band_id,
  class_name: :Album,
  dependent: :destroy

  has_many :tracks,
  through: :albums,
  source: :tracks
end

music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :require_user_to_be_logged_in

  def index
    @bands = Band.all
    render :index
  end

  def show
    @band = Band.find_by(id: params[:id])

    if @band
      render :show
    else
      flash[:errors] = ["Band does not exist"]
      redirect_to bands_url
    end
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to band_url(@band)
    else
      flash[:errors] = @band.errors.full_messages
      redirect_to new_band_url
    end
  end

  def edit
    @band = Band.find_by(id: params[:id])
    render :edit
  end

  def update
    @band = Band.find_by(id: params[:id])

    if @band.update_attributes(band_params)
      redirect_to band_url(@band)
    else
      flash[:errors] = @band.errors.full_messages
      redirect_to edit_band_url(@band)
    end
  end

  def destroy
    @band = Band.find_by(id: params[:id])

    if @band.destroy
      redirect_to bands_url
    else
      flash[:errors] = @band.errors.full_messages
      redirect_to bands_url
    end
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end

end

music_app/app/views/bands/edit.html.erb
<h1>Edit a band</h1>

<%= render 'shared/errors' %>
<div class="form_container">
  <form action="<%= band_url(@band) %>" method="post">
    <input type="hidden" name="_method" value="patch">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label for="band_name">Band Name:</label>
    <input id="band_name" type="text" name="band[name]" value="<%= @band.name %>">
    <br>

  </form>
</div>

<div class="button_container">
  <button type="submit" form="update_band_form">Update band</button>
</div>

<% content_for :footer do %>
  Band edit page
<% end %>

music_app/app/views/bands/index.html.erb
<h1>List of All Bands</h1>

<%= render 'shared/errors' %>

<table>
  <tr>
    <th>Band</th>
    <th>Page</th>
  </tr>
  <% @bands.each do |band| %>
    <tr>
      <td><%= band.name %></td>
      <td><a href="<%= band_url(band) %>">Link</a></td>
    </tr>
  <% end %>
</table>

<div class="button_container">
  <button type="submit" form="create_band_form">Create band</button>
</div>

<form id="create_band_form" action="<%= new_band_url %>" method="get">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
</form>

<% content_for :footer do %>
  Band index page
<% end %>

music_app/app/views/bands/new.html.erb
<h1>Create a band</h1>

<%= render 'shared/errors' %>

<div class="form_container">
  <form action="<%= bands_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label for="band_name">Band Name:</label>
    <input id="band_name"type="text" name="band[name]" value="<%= @band.name %>">
    <br>

    <input type="submit" value="Create band">

  </form>
</div>

<% content_for :footer do %>
  Band new page
<% end %>

music_app/app/views/bands/show.html.erb
<%= render 'shared/errors' %>

<h1>Band: <%= @band.name %></h1>

<div class="button_container">
  <button type="submit" form="back_to_bands_form">Back to bands</button>

  <button type="submit" form="edit_band_form">Edit band</button>

  <button type="submit" form="delete_band_form" name="button">Delete band</button>
</div>

<form id="back_to_bands_form" action="<%= bands_url %>" method="get">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
</form>

<form id="edit_band_form" action="<%= edit_band_url(@band) %>" method="get">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
</form>

<form id="delete_band_form" action="<%= band_url(@band) %>" method="post">
  <input type="hidden" name="_method" value="delete">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
</form>

<br>

<table>
  <tr>
    <th>Album</th>
    <th>Year</th>
    <th>Type</th>
    <th>Page</th>
  </tr>
  <% @band.albums.each do |album| %>
    <tr>
      <td><%= album.title %></td>
      <td><%= album.year %></td>
      <td><%= album.studio ? "Studio" : "Live" %></td>
      <td><a href="<%= album_url(album) %>">Link</a></td>
    </tr>
  <% end %>
</table>

<div class="button_container">
  <button type="submit" form="create_album_form">Create album</button>
</div>

<form id="create_album_form" action="<%= new_band_album_url(@band) %>" method="get">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
</form>

<% content_for :footer do %>
  Band show page
<% end %>